[relaychain]
chain = "polkadot-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
default_command = "./binaries/polkadot-v1.17.0/polkadot"
name = "bob"
validator = true

[[parachains]]
id = 2111
default_command = "./target/release/ciphera-collator"

[[parachains.collators]]
name = "ciphera-contract-collator-01"
